# Generated by Django 3.1.6 on 2021-02-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, default=models.EmailField(max_length=254), max_length=50)),
                ('password_1', models.CharField(max_length=50)),
                ('password_2', models.CharField(max_length=50)),
            ],
        ),
    ]
